name: Deployment pipeline


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker image
        run: |
          cd src
          docker build . -t hello-image
          docker save hello-image > /tmp/image.tar

      - name: Upload Docker image to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello-image
          path: /tmp/image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download Docker image from GitHub Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hello-image
          path: ./image.tar

      - name: Restore docker image
        run: |
          docker load --input ./image.tar